/* shell.js - the page skeleton every practice page shares.
 *
 * Runs BEFORE app.js, because app.js's UI wiring calls getElementById at its top
 * level and would find nothing. It does three things:
 *
 *   1. injects the simulator's own <body> markup, ids and all (the region below
 *      is generated by practice/tools/build.py, so a fix made in
 *      simulator/index.html arrives here by re-syncing rather than by hand);
 *   2. retitles the header for this exercise and adds the Exercise / All problems
 *      buttons;
 *   3. builds the exercise sheet - the dialog that covers the page on load.
 *
 * It is deliberately structure-only. Everything that BEHAVES (loading the
 * skeleton, attaching memory files, opening and closing the sheet) lives in
 * practice.js, which runs after app.js and so can reach the simulator's own
 * functions.
 *
 * The markup region is carried in a String.raw template literal, so it must
 * contain no backtick and no ${ - build.py checks that rather than trusting it.
 */
'use strict';

/* >>> SLICE practice-markup (generated by practice/tools/build.py - do not edit) */
var PRACTICE_MARKUP = String.raw`
  <header class="gh-header">
    <div class="gh-header-inner">
      <a class="gh-mark" href="index.html"><svg viewBox="0 0 58 26" fill="none" stroke="black" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"><path d="M 37.7373 21.25 C 37.752447 18.600017 37.722157 13.899983 37.7373 11.25 C 37.722157 8.899983 35.2373 6.25 32.7373 6.25 C 30.143462 6.25 32.549622 6.25 29.955782 6.25 C 23.70574 6.25 22.45574 11.25 22.501176 13.75 C 22.45574 16.25 23.70574 21.25 29.955782 21.25 C 30.8163 21.25 31.67682 21.25 32.53734 21.25"/><path d="M 2.2184386 2.5 C 2.2184386 7.5 2.2184386 16.25 2.2184386 21.25 C 4.7184386 21.25 7.139786 21.23971 9.999958 21.25 C 16.249958 21.25 17.508377 16.090111 17.499958 13.75 C 17.508377 11.090111 16.249958 6.25 9.999958 6.25 C 8.027672 6.25 9.095067 6.25 7.4284 6.25"/><path d="M 56.0315 6.25 C 53.5315 6.25 53.11017 6.26029 50.25 6.25 C 44 6.25 42.74158 11.409889 42.75 13.75 C 42.74158 16.409889 44 21.25 50.25 21.25 C 52.222286 21.25 54.583635 21.25 56.2503 21.25"/><rect x="47.95" y="13.625" width="8" height=".125"/></svg><span>Baerilog</span></a>
      <nav class="gh-nav"><a href="simulator.html" class="here">Simulator</a><a href="synthesis.html">Synthesizer</a><a href="compiler.html">Compiler</a><a href="index.html">Practice</a></nav>
    </div>
  </header>

  <h1 class="gh-crumb"><a href="index.html">Baerilog</a><span class="sep">/</span><span class="here">Verilog Simulator</span></h1>
  <div class="gh-sub">Write · Simulate · Watch the waveform — all in the browser</div>

  <div class="grid">

    <div class="card layout-pair" id="card-editor">
      <h2><span class="card-collapse-btn" data-collapse>▾</span>Verilog Source Editor
        <span class="help-wrap"><span class="help-icon">?</span><div class="help-popup"><div>&middot; Behavioral subset: module/reg/wire, assign, always @(posedge/negedge/*), initial, if/else, #delay, $display, $finish</div></div></span>
        <span class="header-controls">
          <span class="layout-toggle">
            <span class="layout-btn" id="editorHeightDec" title="Decrease height"><svg viewBox="0 0 45 37.5" fill="currentColor" stroke="none"><rect x="12.5" y="2.5" width="20" height="10"/><rect x="12.5" y="25" width="20" height="10"/><path d="M 2.5 7.5 L 22.5 17.5 L 42.5 7.5 Z"/><path d="M 2.5 30 L 22.5 20 L 42.5 30 Z"/></svg></span>
            <span class="layout-btn" id="editorHeightInc" title="Increase height"><svg viewBox="0 0 45 37.5" fill="currentColor" stroke="none"><rect x="12.5" y="10" width="20" height="7.5"/><rect x="12.5" y="20" width="20" height="7.5"/><path d="M 2.5 25 L 22.5 35 L 42.5 25 Z"/><path d="M 2.5 12.5 L 22.5 2.5 L 42.5 12.5 Z"/></svg></span>
            <span class="layout-btn" id="editorCopyBtn" title="Copy to clipboard">
              <svg viewBox="0 0 16 12" fill="none" stroke="currentColor" stroke-width="1.3"><rect x="1.5" y="3" width="8" height="8" rx="1"/><rect x="6.5" y="0.7" width="8" height="8" rx="1"/></svg>
            </span>
            <span class="layout-btn" id="editorSaveBtn" title="Save to file">
              <svg viewBox="0 0 16 12" fill="none" stroke="currentColor" stroke-width="1.3" stroke-linecap="round" stroke-linejoin="round"><path d="M8 0.8 V7.5 M5 4.5 L8 7.5 L11 4.5"/><path d="M1.5 8.5 V10.2 a1 1 0 0 0 1 1 H13.5 a1 1 0 0 0 1-1 V8.5"/></svg>
            </span>
          </span>
          <span class="layout-toggle">
            <span class="layout-btn" data-layout-btn="side" title="Side by side">
              <svg viewBox="0 0 16 12" fill="none" stroke="currentColor" stroke-width="1.4"><rect x="0.7" y="0.7" width="6.6" height="10.6" rx="1.3"/><rect x="8.7" y="0.7" width="6.6" height="10.6" rx="1.3"/></svg>
            </span>
            <span class="layout-btn" data-layout-btn="stack" title="Stacked">
              <svg viewBox="0 0 16 12" fill="none" stroke="currentColor" stroke-width="1.4"><rect x="0.7" y="0.7" width="14.6" height="4.6" rx="1.3"/><rect x="0.7" y="6.7" width="14.6" height="4.6" rx="1.3"/></svg>
            </span>
          </span>
          <span class="layout-toggle">
            <span class="layout-btn" id="editorHierarchyToggleBtn" title="Show/hide module hierarchy">
              <svg viewBox="0 0 42.5 35" fill="currentColor"><rect x="0" y="0" width="10" height="10"/><rect x="7.5" y="2.5" width="25" height="5"/><rect x="15" y="2.5" width="5" height="30"/><rect x="32.5" y="0" width="10" height="10"/><rect x="17.5" y="15" width="15" height="5"/><rect x="32.5" y="12.5" width="10" height="10"/><rect x="17.5" y="27.5" width="15" height="5"/><rect x="32.5" y="25" width="10" height="10"/></svg>
            </span>
          </span>
        </span>
      </h2>
      <div class="toolbar">
        <button class="btn outline" id="openBtn">Import File</button>
        <span class="time-label">Select from Examples:</span>
        <select id="exampleSelect"></select>
        <input type="file" id="fileOpenInput" accept=".v,.sv,.vh,.txt" style="display:none">
      </div>
      <div id="editorSyncWarning" class="editor-sync-warning" style="display:none"></div>
      <div class="editor-hierarchy-row hierarchy-collapsed" id="editorHierarchyRow">
        <div class="editor-hierarchy-panel" id="editorHierarchyPanel"></div>
        <div class="editor-wrap" id="editorWrap">
          <div class="gutter" id="gutter">1</div>
          <textarea id="codeInput" spellcheck="false"></textarea>
        </div>
      </div>
      <div class="toolbar" style="margin-top:12px; margin-bottom:0;">
        <button class="btn" id="runBtn">▶ Run Simulation</button>
        <button class="btn secondary" id="resetBtn">Reset</button>
        <span class="time-label">run for</span>
        <input class="num-input" id="maxTimeInput" type="number" min="10" step="10" value="300">
        <span class="time-label">time units<span id="maxTimeAutoNote" style="display:none"> (set by $finish)</span></span>
      </div>
    </div>

    <div class="card layout-pair" id="card-testbench">
      <h2><span class="card-collapse-btn" data-collapse>▾</span>Testbench Editor
        <span class="help-wrap"><span class="help-icon">?</span><div class="help-popup"><div>&middot; The stimulus and the checks: everything after the <code>// ======== TESTBENCH ========</code> line, which is what splits one file across these two cards</div><div>&middot; The memory models a design fetches from — a ROM, a RAM, the <code>system</code> wrapper that wires them to the DUT — belong here, not in the design</div><div>&middot; Run compiles both halves together, so this is the same one file it always was; Save writes it back out with the marker in place</div></div></span>
        <span class="header-controls">
          <span class="layout-toggle">
            <span class="layout-btn" id="tbHeightDec" title="Decrease height"><svg viewBox="0 0 45 37.5" fill="currentColor" stroke="none"><rect x="12.5" y="2.5" width="20" height="10"/><rect x="12.5" y="25" width="20" height="10"/><path d="M 2.5 7.5 L 22.5 17.5 L 42.5 7.5 Z"/><path d="M 2.5 30 L 22.5 20 L 42.5 30 Z"/></svg></span>
            <span class="layout-btn" id="tbHeightInc" title="Increase height"><svg viewBox="0 0 45 37.5" fill="currentColor" stroke="none"><rect x="12.5" y="10" width="20" height="7.5"/><rect x="12.5" y="20" width="20" height="7.5"/><path d="M 2.5 25 L 22.5 35 L 42.5 25 Z"/><path d="M 2.5 12.5 L 22.5 2.5 L 42.5 12.5 Z"/></svg></span>
          </span>
          <span class="layout-toggle">
            <span class="layout-btn" data-layout-btn="side" title="Side by side">
              <svg viewBox="0 0 16 12" fill="none" stroke="currentColor" stroke-width="1.4"><rect x="0.7" y="0.7" width="6.6" height="10.6" rx="1.3"/><rect x="8.7" y="0.7" width="6.6" height="10.6" rx="1.3"/></svg>
            </span>
            <span class="layout-btn" data-layout-btn="stack" title="Stacked">
              <svg viewBox="0 0 16 12" fill="none" stroke="currentColor" stroke-width="1.4"><rect x="0.7" y="0.7" width="14.6" height="4.6" rx="1.3"/><rect x="0.7" y="6.7" width="14.6" height="4.6" rx="1.3"/></svg>
            </span>
          </span>
        </span>
      </h2>
      <div class="editor-wrap" id="tbWrap">
        <div class="gutter" id="tbGutter">1</div>
        <textarea id="tbInput" spellcheck="false"></textarea>
      </div>
      <div class="wave-empty" id="tbEmpty" style="display:none">No testbench section in this file — add a <code>// ======== TESTBENCH ========</code> line to split it.</div>
    </div>

    <div class="card full" id="card-console">
      <h2><span class="card-collapse-btn" data-collapse>▾</span>Console
        <span class="help-wrap"><span class="help-icon">?</span><div class="help-popup"><div>&middot; $display output and simulator status</div></div></span>
        <span class="header-controls">
          <span class="layout-toggle">
            <span class="layout-btn" id="consoleHeightDec" title="Decrease height"><svg viewBox="0 0 45 37.5" fill="currentColor" stroke="none"><rect x="12.5" y="2.5" width="20" height="10"/><rect x="12.5" y="25" width="20" height="10"/><path d="M 2.5 7.5 L 22.5 17.5 L 42.5 7.5 Z"/><path d="M 2.5 30 L 22.5 20 L 42.5 30 Z"/></svg></span>
            <span class="layout-btn" id="consoleHeightInc" title="Increase height"><svg viewBox="0 0 45 37.5" fill="currentColor" stroke="none"><rect x="12.5" y="10" width="20" height="7.5"/><rect x="12.5" y="20" width="20" height="7.5"/><path d="M 2.5 25 L 22.5 35 L 42.5 25 Z"/><path d="M 2.5 12.5 L 22.5 2.5 L 42.5 12.5 Z"/></svg></span>
          </span>
        </span>
      </h2>
      <div class="console-box" id="consoleBox"><span class="info">Click Run to simulate…</span></div>
    </div>

    <div class="card full" id="card-model">
      <h2><span class="card-collapse-btn" data-collapse>▾</span>Scoreboard<span class="help-wrap"><span class="help-icon">?</span><div class="help-popup"><div>&middot; Runs a reference model of the AVR subset alongside the design and compares <code>pc</code>, <code>r0</code>–<code>r31</code> and the memories</div><div>&middot; the model implements correct AVR semantics, so a mismatch means the RTL and the ISA disagree</div></div></span></h2>
      <div class="toolbar">
        <label class="mem-radix-toggle">
          <input type="checkbox" id="modelStopCheckbox" checked>
          Stop Simulation when mismatching model
        </label>
        <span class="time-label">after:</span>
        <input class="num-input" id="modelStopAfter" type="number" min="0" step="10" value="10">
        <span class="time-label">time unit</span>
        <label class="mem-radix-toggle">
          <input type="checkbox" id="modelDetailCheckbox">
          Show detail
        </label>
      </div>
      <div class="model-bind" id="modelBind"></div>
      <div class="model-verdict" id="modelVerdict"></div>
      <div class="compare-grid" id="modelGrid"></div>
      <div class="compare-foot" id="modelFoot"></div>
      <div class="wave-empty" id="modelEmpty">No simulation data yet — run a design to compare it against the model.</div>
    </div>

    <div class="split-row hierarchy-collapsed" id="waveSplitRow">
      <div class="card" id="card-hierarchy">
        <h2><span class="card-collapse-btn" data-collapse>▾</span>Module Hierarchy<span class="help-wrap"><span class="help-icon">?</span><div class="help-popup"><div>&middot; click an instance to show or hide its signals &mdash; showing one hides its children, so you descend a level at a time</div><div>&middot; double-click to expand or collapse the branch</div><div>&middot; a memory has no waveform row, so it is shown dimmed and does not respond</div><div>&middot; each name carries its declared bit range, e.g. <code>d[3:0]</code></div></div></span></h2>
        <div class="hierarchy-tree" id="hierarchyTree"></div>
      </div>

      <div class="card" id="card-wave">
        <h2><span class="card-collapse-btn" data-collapse>▾</span>Waveform Viewer
          <span class="help-wrap"><span class="help-icon">?</span><div class="help-popup"><div>&middot; click the chart to move the cursor</div><div>&middot; drag right to zoom into a range, drag left to zoom out, double-click to zoom in</div><div>&middot; wheel sideways &mdash; or shift+wheel &mdash; to pan; on a touchscreen one finger zooms and two fingers pan</div><div>&middot; drag the divider after the names to widen or narrow that column</div><div>&middot; hover a value for its radix menu</div><div>&middot; the <code>[:]</code> button adds each signal's declared bit range to its name</div><div>&middot; show or hide a signal row in the <b>Module Hierarchy</b> panel, not here &mdash; click one, or drag to paint a run of them</div><div>&middot; <b>Turn the plot off</b> frees the canvas, which is the largest allocation on this page &mdash; it grows with the number of shown rows, so hiding rows reclaims it in proportion too. The run itself is unaffected: the Console, the Scoreboard and the Memory Viewer all still work</div></div></span>
        <span class="header-controls">
            <span class="layout-toggle">
              <span class="layout-btn" id="hierarchyToggleBtn" title="Show/hide module hierarchy">
                <svg viewBox="0 0 42.5 35" fill="currentColor"><rect x="0" y="0" width="10" height="10"/><rect x="7.5" y="2.5" width="25" height="5"/><rect x="15" y="2.5" width="5" height="30"/><rect x="32.5" y="0" width="10" height="10"/><rect x="17.5" y="15" width="15" height="5"/><rect x="32.5" y="12.5" width="10" height="10"/><rect x="17.5" y="27.5" width="15" height="5"/><rect x="32.5" y="25" width="10" height="10"/></svg>
              </span>
            </span>
            <span class="layout-toggle">
              <span class="layout-btn" id="waveWidthsBtn" title="Show bit widths on signal names">
                <svg viewBox="0 0 16 12" fill="none" stroke="currentColor" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round"><path d="M5.5 1.2 H2.6 V10.8 H5.5"/><path d="M10.5 1.2 H13.4 V10.8 H10.5"/><circle cx="8" cy="4.4" r="0.95" fill="currentColor" stroke="none"/><circle cx="8" cy="7.6" r="0.95" fill="currentColor" stroke="none"/></svg>
              </span>
            </span>
            <span class="layout-toggle">
              <span class="layout-btn" id="waveExpandBtn" title="Expand to the full browser width">
                <svg viewBox="0 0 16 12" fill="none" stroke="currentColor" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round"><path d="M1 1 V11 M15 1 V11"/><path d="M4.5 6 H11.5 M6.5 3.8 L4.3 6 L6.5 8.2 M9.5 3.8 L11.7 6 L9.5 8.2"/></svg>
              </span>
            </span>
          </span>
        </h2>
        <div class="toolbar" style="margin-bottom:10px;">
          <label class="mem-radix-toggle">
            <input type="checkbox" id="waveOffCheckbox">
            Turn the plot off to save memory
          </label>
          <span class="time-label" id="waveMemNote"></span>
        </div>
        <div class="toolbar" id="waveControls" style="margin-bottom:14px;">
          <div class="toolbar-group">
            <span class="time-label">Zoom</span>
            <button class="btn secondary icon-btn" id="waveZoomIn" title="Zoom in">+</button>
            <span class="zoom-level" id="waveZoomLevel">1.0×</span>
            <button class="btn secondary icon-btn" id="waveZoomOut" title="Zoom out">−</button>
            <button class="btn secondary" id="waveZoomReset">Reset</button>
            <button class="btn secondary icon-btn" id="waveScrollLeft" title="Scroll left">◀</button>
            <button class="btn secondary icon-btn" id="waveScrollRight" title="Scroll right">▶</button>
          </div>
          <div class="toolbar-group">
            <span class="time-label">Start</span>
            <input class="num-input" id="waveStartInput" type="text">
            <span class="time-label">End</span>
            <input class="num-input" id="waveEndInput" type="text">
            <button class="btn" id="waveApplyBtn">Apply</button>
          </div>
        </div>
        <div id="waveScroll">
          <canvas id="waveCanvas" height="120"></canvas>
        </div>
        <div class="wave-empty" id="waveEmpty">No simulation data yet — run a design to see waveforms.</div>
        <div class="badge-row" id="badgeRow"></div>
      </div>
    </div>


    <div class="card full" id="card-memory">
      <h2><span class="card-collapse-btn" data-collapse>▾</span>Memory Viewer<span class="help-wrap"><span class="help-icon">?</span><div class="help-popup"><div>&middot; 2D memory arrays (<code>reg [w:0] name[hi:lo];</code>) declared in the design</div><div>&middot; attach a hex/bin file so <code>$readmemh</code>/<code>$readmemb</code> can load it</div></div></span></h2>
      <div class="toolbar">
        <select id="memorySelect"><option value="">(no memories declared)</option></select>
        <button class="btn secondary" id="memAttachBtn">Attach file(s)…</button>
        <input type="file" id="memFileInput" accept=".hex,.mem,.bin,.txt" multiple style="display:none">
        <label class="mem-radix-toggle">
          <input type="checkbox" id="memHexCheckbox" checked>
          Hexadecimal
        </label>
        <label class="mem-radix-toggle">
          <input type="checkbox" id="memBinCheckbox" checked>
          Binary
        </label>
      </div>
      <div class="mem-file-list" id="memFileList"></div>
      <div class="memory-table-wrap" id="memoryTableWrap">
        <table class="memory-table" id="memoryTable"></table>
      </div>
      <div class="wave-empty" id="memoryEmpty">No memories declared in this design.</div>
    </div>

  </div>

  <div class="footer">© Jeremy Bae 2026 · <a href="https://github.com/jeremyjbae" target="_blank" rel="noopener">github.com/jeremyjbae</a></div>
`;
/* <<< SLICE practice-markup */

var PRACTICE_META = null;      // this page's manifest entry
var PRACTICE_EX = null;        // this page's exercise data, or null if it is missing

/* Small 16px glyphs for the tab strip, in Octicon's shape language but drawn here
 * rather than copied. practice.js uses these; index.html carries its own two, since
 * the hub does not load this file.
 *
 * There is no `wave` entry any more: it was the header mark this file used to build
 * itself, and the header now arrives with the injected markup, carrying the bae
 * wordmark like every other app. */
var ICON = {
  book: '<svg viewBox="0 0 16 16"><path d="M2 2.5A1.5 1.5 0 0 1 3.5 1H13a1 1 0 0 1 1 1v11a1 1 0 0 1-1 1H4a2 2 0 0 0-2 2V2.5Zm2.5-.5a.5.5 0 0 0-.5.5v10.1c.3-.07.63-.1.5-.1h8V2H4.5Z"/></svg>',
  code: '<svg viewBox="0 0 16 16"><path d="M5.7 4.3a.75.75 0 0 1 0 1.06L3.06 8l2.64 2.64a.75.75 0 1 1-1.06 1.06L1.47 8.53a.75.75 0 0 1 0-1.06L4.64 4.3a.75.75 0 0 1 1.06 0Zm4.6 0a.75.75 0 0 1 1.06 0l3.17 3.17a.75.75 0 0 1 0 1.06L11.36 11.7a.75.75 0 1 1-1.06-1.06L12.94 8l-2.64-2.64a.75.75 0 0 1 0-1.06Z"/></svg>',
  term: '<svg viewBox="0 0 16 16"><path d="M1.5 2h13a1 1 0 0 1 1 1v10a1 1 0 0 1-1 1h-13a1 1 0 0 1-1-1V3a1 1 0 0 1 1-1Zm.5 1.5v9h12v-9H2Zm2 2 2 2-2 2 .8.8L7.6 7.5 4.8 4.7 4 5.5Zm4.5 4h4v1h-4v-1Z"/></svg>',
  pulse: '<svg viewBox="0 0 16 16"><path d="M6 2.5a.75.75 0 0 1 .7.48L9.3 10l1-2.5a.75.75 0 0 1 .7-.5h4v1.5h-3.5l-1.8 4.5a.75.75 0 0 1-1.4 0L5.7 5.5 4.7 8a.75.75 0 0 1-.7.5H0V7h3.5l1.8-4.02A.75.75 0 0 1 6 2.5Z"/></svg>',
  db: '<svg viewBox="0 0 16 16"><path d="M8 1c3.3 0 6 .9 6 2v10c0 1.1-2.7 2-6 2s-6-.9-6-2V3c0-1.1 2.7-2 6-2Zm4.5 4.6C11.4 6.1 9.8 6.4 8 6.4s-3.4-.3-4.5-.8V8c.6.4 2.3.9 4.5.9s3.9-.5 4.5-.9V5.6ZM8 2.5c-2.5 0-4.5.4-4.5 1s2 1 4.5 1 4.5-.4 4.5-1-2-1-4.5-1Zm4.5 7.1c-1.1.5-2.7.8-4.5.8s-3.4-.3-4.5-.8V12c.6.4 2.3.9 4.5.9s3.9-.5 4.5-.9V9.6Z"/></svg>',
  chip: '<svg viewBox="0 0 16 16"><path d="M5 1.5h1.5v1.5h3V1.5H11v1.5h1.5A1.5 1.5 0 0 1 14 4.5V6h1.5v1.5H14v1H15.5V10H14v1.5a1.5 1.5 0 0 1-1.5 1.5H11v1.5H9.5V13h-3v1.5H5V13H3.5A1.5 1.5 0 0 1 2 11.5V10H.5V8.5H2v-1H.5V6H2V4.5A1.5 1.5 0 0 1 3.5 3H5V1.5Zm-1.5 3v7h9v-7h-9Zm2 2h5v3h-5v-3Z"/></svg>',
  /* Two more for the navigation drawer below. `home` is new; every other row reuses
     one of the tab strip's glyphs above rather than starting a second icon language -
     the simulator IS the waveform app, the synthesizer emits gates, the compiler
     emits code, and `book` is what the Exercise tab already means. */
  home: '<svg viewBox="0 0 16 16"><path d="M8 1.2 15 7l-.94 1.15-1.06-.88V14a1 1 0 0 1-1 1H9.5v-4.5h-3V15H4a1 1 0 0 1-1-1V7.27l-1.06.88L1 7 8 1.2Zm4 4.83L8 2.7 4 6.03V13.5h1V9h6v4.5h1V6.03Z"/></svg>',
  menu: '<svg viewBox="0 0 16 16"><path d="M1.5 3.25h13v1.5h-13v-1.5Zm0 4h13v1.5h-13v-1.5Zm0 4h13v1.5h-13v-1.5Z"/></svg>'
};

/* The drawer's rows, in order. `href` is a bare filename because Baerilog/ is flat
 * and every page finds its siblings that way; Home is the one link that leaves the
 * site. The three apps outside this directory (emulator, verify, workbench) are
 * deliberately absent: they live one level ABOVE the deployed root, so a `../` row
 * would resolve in the repo and 404 on the site - they join once they are published
 * as siblings of these pages. */
var NAV_ITEMS = [
  { label: 'Home', href: 'https://jeremyjbae.github.io/Baerilog', icon: 'home' },
  { label: 'Practice', href: 'index.html', icon: 'book' },
  { label: 'Simulator', href: 'simulator.html', icon: 'pulse' },
  { label: 'Synthesizer', href: 'synthesis.html', icon: 'chip' },
  { label: 'Compiler', href: 'compiler.html', icon: 'code' }
];

(function () {
  var slug = window.PRACTICE_SLUG;
  PRACTICE_META = (window.PRACTICE_MANIFEST || []).filter(function (e) {
    return e.slug === slug;
  })[0] || { slug: slug, title: slug, category: '', level: 0 };
  PRACTICE_EX = (window.PRACTICE_EXERCISES || {})[slug] || null;

  /* ---- 1. the simulator, verbatim ---- */
  document.body.insertAdjacentHTML('afterbegin', PRACTICE_MARKUP);

  /* ---- 2. the page chrome ----
     The header bar arrives with the injected markup, because it is the simulator's
     own - the same markup every app carries, so it cannot drift into a lookalike.
     Only two things are wrong for a practice page: the nav marks Simulator as the
     current app, and the heading is the simulator's. Both are fixed here.

     The tab strip is created EMPTY and filled by practice.js, because which tabs
     exist depends on which cards the page has - and the CPU / Memory Model card
     decides its own visibility during a run, which has not happened yet. A tab
     pointing at a card that is not there is a dead control. */
  // Scoped to the nav element rather than written as a descendant selector: a
  // single-element selector is all the stub DOM the harnesses use can resolve, and
  // a silently-empty NodeList would leave the marker on Simulator.
  var nav = document.querySelector('.gh-nav');
  if (nav) {
    var navLinks = nav.querySelectorAll('a');
    for (var i = 0; i < navLinks.length; i++) {
      // The hub is index.html - it no longer has 'practice' in its href, so matching
      // on that would mark nothing here and leave Simulator looking current.
      var href = navLinks[i].getAttribute('href') || '';
      navLinks[i].className = href === 'index.html' ? 'here' : '';
    }
  }

  var h1 = document.querySelector('h1');
  // `.gh-sub` since simulator.html's own markup carries the breadcrumb shape now -
  // this used to read `.subtitle`, and a rename there without this returns null and
  // throws on every one of the twenty pages.
  var sub = document.querySelector('.gh-sub');

  /* The breadcrumb IS the h1, the way a repo page's owner/name is - the slug is the
     last segment, and the human title moves to the line under it. */
  h1.className = 'gh-crumb';
  h1.innerHTML = '<a href="index.html">practice</a>'
               + '<span class="sep">/</span>'
               + '<span class="here">' + escapeHtml(PRACTICE_META.slug) + '</span>'
               + '<span class="gh-label">' + escapeHtml(levelText()) + '</span>';
  sub.className = 'gh-sub';
  sub.textContent = PRACTICE_META.title
                  + (PRACTICE_META.blurb ? ' — ' + PRACTICE_META.blurb : '');

  var tabs = mk('nav', 'exTabs', 'gh-tabs');
  h1.parentElement.insertBefore(tabs, sub.nextSibling);

  function levelText() {
    return [PRACTICE_META.category, PRACTICE_META.level ? 'Level ' + PRACTICE_META.level : '']
      .filter(Boolean).join(' · ');
  }

  /* ---- 3. the exercise sheet ----
     Built out of real elements rather than one innerHTML string, so the
     description is set on the body element itself. That keeps the sheet's parts
     addressable (practice.js finds each by id) instead of existing only as text
     inside a parent. */
  var backdrop = mk('div', 'exBackdrop', 'ex-backdrop open');
  var sheet = mk('div', 'exSheet', 'ex-sheet');
  sheet.setAttribute('role', 'dialog');
  sheet.setAttribute('aria-modal', 'true');
  sheet.setAttribute('aria-labelledby', 'exSheetTitle');

  var shead = mk('div', null, 'ex-sheet-head');
  shead.appendChild(mk('span', null, 'ex-kicker', 'Exercise'));
  shead.appendChild(mk('span', 'exSheetTitle', 'ex-sheet-title', PRACTICE_META.title));
  shead.appendChild(mk('span', null, 'ex-sheet-meta', levelText()));
  var close = mk('button', 'exCloseBtn', 'ex-close', '✕');
  close.setAttribute('title', 'Close');
  close.setAttribute('aria-label', 'Close');
  shead.appendChild(close);

  var sbody = mk('div', 'exSheetBody', 'ex-sheet-body');
  sbody.innerHTML = PRACTICE_EX && PRACTICE_EX.descriptionHtml
    ? PRACTICE_EX.descriptionHtml
    : '<p>This exercise has no description yet.</p>';

  var sfoot = mk('div', null, 'ex-sheet-foot');
  sfoot.appendChild(mk('button', 'exStartBtn', 'btn ex-start', 'Get Started!'));

  sheet.appendChild(shead);
  sheet.appendChild(sbody);
  sheet.appendChild(sfoot);
  backdrop.appendChild(sheet);
  // Appended already carrying `open`, so the prompt covers the page from the
  // moment it exists rather than after a repaint; practice.js re-opens it to lock
  // body scroll and place focus, and owns every way out of it.
  document.body.appendChild(backdrop);

  /* ---- 4. the navigation drawer ----
     Not here: the builder is tools/navmenu.js, pasted into this file and into all six
     apps by tools/navmenu.py, so a practice page and an app cannot end up with
     different drawers. The region is at the foot of this file. ---- */

  function mk(tag, id, cls, text) {
    var e = document.createElement(tag);
    if (id) e.id = id;
    if (cls) e.className = cls;
    if (text) e.textContent = text;
    return e;
  }

  function escapeHtml(s) {
    return String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
  }
})();


